name: Publish package to npmjs
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo GITHUB_REF#refs/tags/ | | sed -e "s/v//g")
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Publish package  
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        run: yarn install --frozen-lockfile && yarn publish --access public --new-version ${{ steps.get_version.outputs.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
